### ISSUE TITLE
Unicode characters

### ISSUE THREAD

**Issue by rob1997** [powerpoint45/QuickMemo-lqm-to-txt-File-Converter#3]
Hey, very great work!

but I had this issue where I wanna convert a memo with non English characters and it replaces it with "?", could you update it to support all characters, or at least direct me to class with that function/responsibility so I can edit it a bit.

thank you and really awesome work!

**Comment by Aizistral** [comment]
I have created a similar tool of my own which does fully support unicode characters: https://github.com/Aizistral-Studios/LQM-Converter/releases/tag/v1.0.0

**Comment by rob1997** [comment]
Oh hey, been a while > a year. Yeah I just made my own tool using C# and extracted the text I needed, thank you though! I'll just close the issue.
