### ISSUE TITLE
Firewall warns me about malware and trojan

### ISSUE THREAD

**Issue by Nestak2** [powerpoint45/QuickMemo-lqm-to-txt-File-Converter#4]
I tried to download the main file as described by the youtube tutorial by the author. But my firewall (Bytefence) warns me that there is malware coming with the file. Is there a problem with my firewall or is there something fishy with the file?

**Comment by Anderscam** [comment]
Yeah me too. Such a shame as it appears to be the only decent option to get notes from QuickMemo+ :-(

**Comment by bbrown1205** [comment]
In the YouTube video comments, the **Lucid Dev Team** responded with:  What? This program wasn't even written in JavaScript.

I have several hundred Memo I need converted. Such a shame indeed.

**Comment by powerpoint45** [comment]
This is not malware. People are free to decompile the jar and check it out, or you can compile it for yourself. I don't know why it would show up on security software. This doesn't even use the internet
